// GENERATED by scripts/update-openai-pricing.ts - do not edit by hand.
// Source per model is noted inline; see openaiPricingUpdate.ts for the
// sources, validation rules and the official-rate guard.

import type { ModelPricing } from "./pricing"

/** OpenAI list prices, USD per 1M tokens. */
export const OPENAI_MODEL_PRICING: Record<string, ModelPricing> = {
  "gpt-5": { inputPerMTok: 1.25, outputPerMTok: 10, cacheReadPerMTok: 0.125, cacheWritePerMTok: 1.25 }, // models.dev
  "gpt-5-codex": { inputPerMTok: 1.25, outputPerMTok: 10, cacheReadPerMTok: 0.125, cacheWritePerMTok: 1.25 }, // litellm
  "gpt-5-mini": { inputPerMTok: 0.25, outputPerMTok: 2, cacheReadPerMTok: 0.025, cacheWritePerMTok: 0.25 }, // models.dev
  "gpt-5-nano": { inputPerMTok: 0.05, outputPerMTok: 0.4, cacheReadPerMTok: 0.005, cacheWritePerMTok: 0.05 }, // models.dev
  "gpt-5.1": { inputPerMTok: 1.25, outputPerMTok: 10, cacheReadPerMTok: 0.125, cacheWritePerMTok: 1.25 }, // models.dev
  "gpt-5.1-codex-max": { inputPerMTok: 1.25, outputPerMTok: 10, cacheReadPerMTok: 0.125, cacheWritePerMTok: 1.25 }, // litellm
  "gpt-5.1-codex-mini": { inputPerMTok: 0.25, outputPerMTok: 2, cacheReadPerMTok: 0.025, cacheWritePerMTok: 0.25 }, // litellm
  "gpt-5.2": { inputPerMTok: 1.75, outputPerMTok: 14, cacheReadPerMTok: 0.175, cacheWritePerMTok: 1.75 }, // models.dev
  "gpt-5.2-codex": { inputPerMTok: 1.75, outputPerMTok: 14, cacheReadPerMTok: 0.175, cacheWritePerMTok: 1.75 }, // litellm
  "gpt-5.3-codex": { inputPerMTok: 1.75, outputPerMTok: 14, cacheReadPerMTok: 0.175, cacheWritePerMTok: 1.75 }, // models.dev
  "gpt-5.3-codex-spark": { inputPerMTok: 1.75, outputPerMTok: 14, cacheReadPerMTok: 0.175, cacheWritePerMTok: 1.75 }, // models.dev
  "gpt-5.4": { inputPerMTok: 2.5, outputPerMTok: 15, cacheReadPerMTok: 0.25, cacheWritePerMTok: 2.5 }, // models.dev
  "gpt-5.4-mini": { inputPerMTok: 0.75, outputPerMTok: 4.5, cacheReadPerMTok: 0.075, cacheWritePerMTok: 0.75 }, // models.dev
  "gpt-5.4-nano": { inputPerMTok: 0.2, outputPerMTok: 1.25, cacheReadPerMTok: 0.02, cacheWritePerMTok: 0.2 }, // models.dev
  "gpt-5.5": { inputPerMTok: 5, outputPerMTok: 30, cacheReadPerMTok: 0.5, cacheWritePerMTok: 5 }, // models.dev
  "gpt-5.6": { inputPerMTok: 4, outputPerMTok: 20, cacheReadPerMTok: 0.4, cacheWritePerMTok: 5 }, // models.dev
  "gpt-5.6-cyber": { inputPerMTok: 12.5, outputPerMTok: 75, cacheReadPerMTok: 1.25, cacheWritePerMTok: 15.625 }, // litellm
  "gpt-5.6-luna": { inputPerMTok: 0.2, outputPerMTok: 1.2, cacheReadPerMTok: 0.02, cacheWritePerMTok: 0.25 }, // models.dev
  "gpt-5.6-sol": { inputPerMTok: 4, outputPerMTok: 20, cacheReadPerMTok: 0.4, cacheWritePerMTok: 5 }, // models.dev
  "gpt-5.6-terra": { inputPerMTok: 2, outputPerMTok: 12, cacheReadPerMTok: 0.2, cacheWritePerMTok: 2.5 }, // models.dev
  "gpt-6-astra": { inputPerMTok: 10, outputPerMTok: 50, cacheReadPerMTok: 1, cacheWritePerMTok: 12.5 }, // models.dev
  "gpt-6-luna": { inputPerMTok: 0.1, outputPerMTok: 0.5, cacheReadPerMTok: 0.01, cacheWritePerMTok: 0.125 }, // models.dev
  "gpt-6-sol": { inputPerMTok: 2, outputPerMTok: 10, cacheReadPerMTok: 0.2, cacheWritePerMTok: 2.5 }, // models.dev
  "gpt-daybreak-blue-latest": { inputPerMTok: 4, outputPerMTok: 20, cacheReadPerMTok: 0.4, cacheWritePerMTok: 5 }, // litellm
  "gpt-daybreak-red-latest": { inputPerMTok: 12.5, outputPerMTok: 75, cacheReadPerMTok: 1.25, cacheWritePerMTok: 15.625 }, // litellm
}
