import { afterEach, beforeEach, expect, it } from "bun:test"
import { randomUUID } from "node:crypto"
import { lstatSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { isUuidV4 } from "../proxy/session/bookkeeping/uuid"
import type { UuidV4 } from "../proxy/session/bookkeeping/uuid"
import { privateName } from "../proxy/session/bookkeeping/privateNames"
import type { PrivatePath } from "../proxy/session/bookkeeping/privateNames"
import { BookkeepingFormatError } from "../proxy/session/bookkeeping/storagePaths"
import { PrivateIdentityError, resumeFileRetirement } from "../proxy/session/bookkeeping/privateRetirement"
import { JOURNAL_NAME, observeSource, readJournal, SOURCE_NAMES } from "../proxy/session/bookkeeping/maintenanceJournal"
import { EXPORT_JOURNAL_NAME, readExportJournal } from "../proxy/session/bookkeeping/exportJournal"
import { CYCLE_TRANSITION_NAME, readTransition } from "../proxy/session/bookkeeping/cycles"
import { runBookkeepingCli } from "../proxy/session/bookkeeping/cli"

let directory: string
beforeEach(() => {
  directory = realpathSync(mkdtempSync(join(tmpdir(), "bookkeeping-uuid-")))
  writeFileSync(join(directory, "keep"), "never rename or delete", { mode: 0o600 })
})
afterEach(() => { rmSync(directory, { recursive: true, force: true }) })
const malformed = {
  zeros: "00000000-0000-0000-0000-000000000000",
  version: "aaaaaaaa-aaaa-1aaa-8aaa-aaaaaaaaaaaa",
  variant: "aaaaaaaa-aaaa-4aaa-7aaa-aaaaaaaaaaaa",
  uppercase: "AAAAAAAA-AAAA-4AAA-8AAA-AAAAAAAAAAAA",
  unstructured: "a".repeat(36),
}
const snapshot = () => readdirSync(directory).sort().map((name) => {
  const path = join(directory, name)
  const stat = lstatSync(path)
  return { name, ino: stat.ino, dev: stat.dev, mode: stat.mode, bytes: readFileSync(path).toString("hex") }
})
function formatRefusal(operation: () => unknown): void {
  try { operation(); throw new Error("invalid UUID accepted") } catch (error) {
    expect(error).toBeInstanceOf(BookkeepingFormatError)
    expect((error as BookkeepingFormatError).exitCode).toBe(5)
  }
}

it("narrows only lowercase UUID v4 generated by Node", () => {
  const consume = (value: UuidV4) => value
  for (let i = 0; i < 100; i++) {
    const value: unknown = randomUUID()
    expect(isUuidV4(value)).toBe(true)
    if (!isUuidV4(value)) throw new Error("Node randomUUID did not generate v4")
    expect(consume(value)).toBe(value)
  }
  for (const value of [...Object.values(malformed), null, undefined, 4, {}, "", randomUUID() + "x"]) {
    expect(isUuidV4(value)).toBe(false)
  }
})

for (const [label, invalid] of Object.entries(malformed)) {
  for (const field of ["migration-id", "release-suffix", "export-id", "export-migration-id", "cycle-id", "cycle-file"] as const) {
    it(`rejects ${label} in ${field} with typed 5 and unchanged files/inodes`, async () => {
      const id = randomUUID()
      const file = { name: JOURNAL_NAME, digest: "a".repeat(64), bytes: 0 }
      let path: string
      let value: unknown
      let read: () => unknown
      if (field === "migration-id" || field === "release-suffix") {
        path = JOURNAL_NAME
        value = { format: "meridian-bookkeeping-migration", version: 1, targetVersion: 1,
          id: field === "migration-id" ? invalid : id, phase: "PREPARED",
          sources: SOURCE_NAMES.map((source) => observeSource(directory, source).identity),
          ...(field === "release-suffix" ? { releases: { "sessions.json": {
            name: `sessions.json.lock.releasing-${id}-${invalid}`, dev: 0, ino: 0,
          } } } : {}) }
        read = () => readJournal(directory, true)
      } else if (field === "export-id" || field === "export-migration-id") {
        path = EXPORT_JOURNAL_NAME
        value = { format: "meridian-bookkeeping-export", version: 1,
          id: field === "export-id" ? invalid : id, migrationId: field === "export-migration-id" ? invalid : id,
          phase: "PREPARED", resources: 0, mappings: 0,
          documents: SOURCE_NAMES.map((name) => ({ ...file, name })) }
        read = () => readExportJournal(directory, true)
      } else {
        path = CYCLE_TRANSITION_NAME
        value = { version: 1, id: field === "cycle-id" ? invalid : id,
          files: field === "cycle-file" ? [{ ...file, name: `session-bookkeeping.sqlite.exported-${invalid}` }, file] : [file] }
        read = () => readTransition(directory, true)
      }
      writeFileSync(join(directory, path), JSON.stringify(value), { mode: 0o600 })
      const before = snapshot()
      formatRefusal(read)
      expect(snapshot()).toEqual(before)
      expect(await runBookkeepingCli(["migrate", "--session-dir", directory, "--writers-stopped", "--json"])).toBe(5)
      expect(snapshot()).toEqual(before)
    })
  }
  it(`does not manufacture a PrivatePath from ${label}`, () => {
    const id = randomUUID()
    const publicPath = join(directory, "keep")
    const before = snapshot()
    let result: PrivatePath | undefined
    formatRefusal(() => { result = privateName(publicPath, id, `${publicPath}.releasing-${id}-${invalid}`) })
    expect(result).toBeUndefined()
    formatRefusal(() => privateName(publicPath, invalid))
    expect(snapshot()).toEqual(before)
  })
  for (const field of ["id", "private"] as const) it(`rejects ${label} retirement ${field} without mutation`, () => {
    const source = join(directory, "keep")
    const id = randomUUID()
    const stat = lstatSync(source)
    const journal = privateName(source + ".deletion-intent", id)
    writeFileSync(journal, JSON.stringify({ source,
      private: field === "private" ? `${source}.releasing-${id}-${invalid}` : privateName(source, id),
      id: field === "id" ? invalid : id,
      dev: stat.dev, ino: stat.ino }), { mode: 0o600 })
    const before = snapshot()
    try { resumeFileRetirement(source); throw new Error("invalid UUID accepted") } catch (error) {
      expect(error).toBeInstanceOf(field === "id" ? PrivateIdentityError : BookkeepingFormatError)
      expect((error as { exitCode: number }).exitCode).toBe(5)
    }
    expect(snapshot()).toEqual(before)
  })
}
